version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "task-management-api-app"
    ports:
      - "${HOST_PORT}:${PORT}"
    volumes:
      - ./src:/app
      - /app/node_modules
    command: "yarn dev"
    networks:
      - default
    environment:
      - PORT=${PORT}
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
